version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: batproai
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d batproai || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 15

  api:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - apps/backend/.env.production
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "4000"
    ports:
      - "4000:4000"  # pratique pour tester l'API directe en local

  web:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  pgdata:
