version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: batproai
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d batproai || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 15
    restart: unless-stopped

  api:
    image: ghcr.io/${REGISTRY_OWNER}/batproai-api:latest
    env_file:
      - ../../apps/backend/.env.production
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "4000"
    restart: unless-stopped

  web:
    image: ghcr.io/${REGISTRY_OWNER}/batproai-web:latest
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  pgdata:
